var mainGrammar = {
    "origin": [
"Il est #accroche#, #lieu# qui les #verbe# est #complément# par #détail#, dont #caractéristique# n’est pas #comparateur# #nombre# lieues, suivant #géographe#. \\#GeoVerneBot"],
    "accroche": ["admis", "assuré", "attesté", "avéré", "certain", "clair", "constaté", "déclaré", "démontré", "établi", "fondé", "incontestable", "indéniable", "indiscutable", "indubitable", "irrécusable", "irréfragable", "irréfutable", "manifeste", "notoire", "reconnu", "sûr", "vrai"],
    "lieu": ["l'arche", "l'exsurgence", "la baie", "la barkhane", "la barre", "la butte", "la caldeira", "la calanque", "la chute d'eau", "la colline", "la combe", "la côte", "la crevasse", "la cuesta", "la doline", "la dune", "la falaise", "la forêt ", "la gorge", "la gorge", "la garrigue", "la lagune", "la lagune", "la mer", "la mesa", "la moraine", "la péninsule", "la plage", "la plaine", "la reculée", "la ria", "la rivière", "la rizière", "la sebkha", "la source", "la steppe", "la terrasse", "la tourbière", "la tufière", "la vallée"],
    "verbe": ["baigne", "jouxte", "borde", "encadre", "entoure", "prolonge", "limite", "longe", "flanque"],
    "complément": ["circonscrite", "entourée", "ensérrée", "encadrée", "ourlée", "enfermée", "ceinturée", "bordée", "enveloppée", "hérissée", "enclavée", "surplombée", "dominée", "surmontée"],
    "détail": ["une ceinture de récifs coralligènes", "une anse semi-circulaire, que ses pointes aiguës protégeaient contre les ondulations du large", "des montagnes, à deux pas d’un gouffre dans lequel le moindre mouvement m’eût précipité", "les défilés des montagnes de Sutpour", "des montagnes couvertes de verdure, les champs d’orge, de maïs et de froment, des rios et des étangs peuplés d’alligators verdâtres", "les pittoresques montagnes de Saddle-Peak", "des îlots montagneux très-escarpés", "des anses dont il n'eût vérifié le brassiage et les accores", "un cordon de récifs et d'îlots désolés", "des montagnes qui dominent cette contrée", "les hautes montagnes de Malacca, dont les forêts abritent les plus beaux tigres de la terre", "les montagnes très-ramifiées des Ghâtes-Occidentales", "les montagnes Wahsatch", "les massifs montagneux qui s’arrondissent au Sud jusqu’aux sources de la rivière de l’Arkansas", "un port abrité des mauvais vents par un amphithéâtre de montagnes", "les vallées, arrosées par les eaux des montagnes, tapissées de cette herbe envahissante nommée menervia", "les sommets de ces montagnes sous-marines, dont la chaîne se prolonge du nord-ouest au sud-est jusqu’aux Marquises et à l’île Pitcairn", "ces terres imprégnées des chaleurs estivales et arrosées des multiples rios descendus des montagnes", "les divers rios d’eaux vives des montagnes voisines, dont l’une porte l’appareil sémaphorique", "des montagnes, dont les cimes pointent au-dessus du dôme des frondaisons"],
    "caractéristique": ["la circonférence", "la longueur", "la dimension", "la taille", "la largeur", "la profondeur", "l'extension", "le calibre", "l'envergure", "l'étendue", "l'importance", "le développement", "l'empan", "l'élévation", "l'ampleur"],
    "comparateur": ["inférieure à", "supérieure à"],
    "nombre": ["cent dix", "cinquante-quatre", "deux cent ", "deux cents", "deux cents", "quatre-vingt-neuf", "six cent cinquante", "soixante et une", "soixante-huit", "trente-huit", "trente-six", "vingt-six"],
    "géographe": ["Alexander von Humboldt", "Carl Ritter", "Élisée Reclus ", "Friedrich Ratzel", "Paul Vidal de la Blache", "Victor Adolphe Malte-Brun", "William Morris Davis"]
};

module.exports = mainGrammar;
